apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: meureplicaset
spec: 
  replicas: 4
  selector:
    matchLabels:
      app: web
  template: 
    metadata: 
      labels:
        app: web
    spec: 
      containers:
        - name: web
          image: kubedevio/web-page:green
          ports: 
            - containerPort: 80